<#
.SYNOPSIS
    One-time local setup: generates the HTTPS development certificate and a .env with
    strong random secrets.

.DESCRIPTION
    Safe to re-run. Existing files are left alone unless -Force is passed, so this will
    never silently rotate a password that a running database is already using.

.EXAMPLE
    ./scripts/setup.ps1
    docker compose up -d
#>
[CmdletBinding()]
param(
    # Overwrite an existing .env and re-export the certificate.
    [switch]$Force,

    # Also install the certificate into the trust store. Left off by default because it
    # modifies a machine-wide security setting and prompts for elevation — your call, not
    # a side effect of running setup.
    [switch]$TrustCertificate
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $repoRoot '.env'
$certDir = Join-Path $env:USERPROFILE '.aspnet\https'
$certFile = Join-Path $certDir 'LineOps.Web.pfx'

function New-Secret {
    $bytes = New-Object byte[] 24
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    ([Convert]::ToBase64String($bytes) -replace '[+/=]', '')
}

if ((Test-Path $envFile) -and -not $Force) {
    Write-Host ".env already exists — leaving it alone (pass -Force to regenerate)." -ForegroundColor Yellow
    Write-Host "Note: regenerating POSTGRES_PASSWORD will not match an existing database volume." -ForegroundColor Yellow
    $certPassword = (Select-String -Path $envFile -Pattern '^CERT_PASSWORD=(.*)$').Matches.Groups[1].Value
}
else {
    $certPassword = New-Secret
    $dbPassword = New-Secret

    @"
# Local secrets. Gitignored — never commit this file.
# Generated by scripts/setup.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm').

POSTGRES_PASSWORD=$dbPassword
CERT_PASSWORD=$certPassword
CERT_PATH=`${USERPROFILE}/.aspnet/https
HTTPS_PORT=9443

# Provider keys — blank runs on the free demo and ESPN sources.
ODDS_API_IO_KEY=
THE_ODDS_API_KEY=
BALLDONTLIE_KEY=
"@ | Set-Content -Path $envFile -Encoding utf8

    Write-Host "Wrote .env with fresh secrets." -ForegroundColor Green
}

if (-not (Test-Path $certDir)) {
    New-Item -ItemType Directory -Force -Path $certDir | Out-Null
}

if ((Test-Path $certFile) -and -not $Force) {
    Write-Host "Certificate already present at $certFile" -ForegroundColor Yellow
}
else {
    # Export only. The private key stays on this machine and the PFX is mounted read-only
    # into the container; it is never copied into an image layer.
    dotnet dev-certs https -ep $certFile -p $certPassword | Out-Null
    Write-Host "Exported development certificate to $certFile" -ForegroundColor Green
}

if ($TrustCertificate) {
    dotnet dev-certs https --trust
}
else {
    Write-Host ""
    Write-Host "The certificate is not trusted yet. To avoid browser warnings, run:" -ForegroundColor Cyan
    Write-Host "    dotnet dev-certs https --trust" -ForegroundColor Cyan
    Write-Host "(this modifies your machine's trust store, so it is deliberately opt-in)" -ForegroundColor DarkGray
}

Write-Host ""
Write-Host "Next:" -ForegroundColor Cyan
Write-Host "    docker compose up -d" -ForegroundColor White
Write-Host "    https://localhost:$(if ($env:HTTPS_PORT) { $env:HTTPS_PORT } else { '9443' })" -ForegroundColor White
